export const auth = {
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
    FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
    FETCH_CURRENT_FAILURE: 'FETCH_CURRENT_FAILURE',
    REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
};

export const restaurants = {
    FETCH_RESTAURANT: 'FETCH_RESTAURANT',
    FETCH_RESTAURANT_SUCCESS: 'FETCH_RESTAURANT_SUCCESS',
    FETCH_RESTAURANT_FAILURE: 'FETCH_RESTAURANT_FAILURE',
    FETCH_ALL_RESTAURANTS: 'FETCH_ALL_RESTAURANTS',
    FETCH_ALL_RESTAURANTS_SUCCESS: 'FETCH_ALL_RESTAURANTS_SUCCESS',
    FETCH_ALL_RESTAURANTS_FAILURE: 'FETCH_ALL_RESTAURANTS_FAILURE',
    FETCH_SEARCHING_LIST: 'FETCH_SEARCHING_LIST',
    FETCH_SEARCHING_LIST_SUCCESS: 'FETCH_SEARCHING_LIST_SUCCESS',
    FETCH_SEARCHING_LIST_FAILURE: 'FETCH_SEARCHING_LIST_FAILURE'
};

export const products = {
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILURE: 'FETCH_ALL_PRODUCTS_FAILURE',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    DELETE_WITH_CART: 'DELETE_WITH_CART',
    DELETE_WITH_CART_SUCCESS: 'DELETE_WITH_CART_SUCCESS',
    DELETE_WITH_CART_FAILURE: 'DELETE_WITH_CART_FAILURE',
    CREATE_ORDER: 'CREATE_ORDER',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
    FETCH_ALL_ORDERS: 'FETCH_ALL_ORDERS',
    FETCH_ALL_ORDERS_SUCCESS: 'FETCH_ALL_ORDERS_SUCCESS',
    FETCH_ALL_ORDERS_FAILURE: 'FETCH_ALL_ORDERS_FAILURE',
    FETCH_ORDER: 'FETCH_ORDER',
    FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS',
    FETCH_ORDER_FAILURE: 'FETCH_ORDER_FAILURE',
    CHANGE_ORDER_STATUS: 'CHANGE_ORDER_STATUS',
    CHANGE_ORDER_STATUS_SUCCESS: 'CHANGE_ORDER_STATUS_SUCCESS',
    CHANGE_ORDER_STATUS_FAILURE: 'CHANGE_ORDER_STATUS_FAILURE',
};

export const users = {
    FETCH_USER: 'FETCH_USER',
    FETCH_ALL_USERS: 'FETCH_ALL_USERS',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    FETCH_ALL_USER_FAILURE: 'FETCH_ALL_USER_FAILURE',
};
